### ISSUE TITLE
Upgrades and Attributes

### ISSUE THREAD

**Issue by NeoFalcon1605** [elBukkit/MagicPlugin#927] opened 2021-06-21 16:14 UTC
Applying an upgrade that has an attribute to a wand stops any attributes on the wand changing
[Github Report Files.zip](https://github.com/elBukkit/MagicPlugin/files/6688043/Github.Report.Files.zip)

**Comment by NathanWolf** [comment] 2021-08-23 20:44
Sorry I completely missed this report and it's been months :(

I see the problem is still there, slotted upgrades completely replace wand properties and don't get merged with any existing properties.

I will need to think on how to improve this.

**Comment by NathanWolf** [comment] 2021-08-24 04:06
Well again sorry it took me so long, but this will be fixed in the next dev build: 

https://jenkins.elmakers.com/job/MagicPlugin/3918/

**Closed by NathanWolf** 2021-08-24 04:06 UTC
Labels: Bug
