### ISSUE TITLE
Death wipes out inventory 

### ISSUE THREAD

**Issue by BruBread** [elBukkit/MagicPlugin#817] opened 2020-12-12 19:20 UTC
I’m using Magic 8.1.1 and from time to time, whenever someone died it would delete everything in their inventory besides the magic items. Running it on 1.16.4 Rn.

**Comment by NathanWolf** [comment] 2020-12-12 19:54
Do you have other plugins that would be keeping items or otherwise manipulating the inventory on death?

**Comment by BruBread** [comment] 2020-12-12 20:20
Uh none that modify the inventory besides magic

**Comment by NathanWolf** [comment] 2020-12-12 20:22
Hm- well sorry about that. If I can't reproduce it, it will be very difficult for me to fix- I assume there is something different about your server, but maybe not. You've checked the logs for errors?

**Comment by BruBread** [comment] 2020-12-12 20:30
Ah it’s understandable if you can’t be able to reproduce it, and none out of the inventory besides server overloads

**Comment by NathanWolf** [comment] 2020-12-16 16:10
marcel on Discord reported something that's probably related, but oddly their issue was that sometimes they *wouldn't* lose items on death. 

So something does seem odd here, I'd like to get this figured out before releasing 8.2

**Comment by Moss-And-Bone** [comment] 2021-02-16 00:48
I have had one player, in particular, run into this issue several times, but not always the same exact way. Often It happens when getting kicked for ping/crash while on a broom and then using recall to go to death spot, but the spell takes them slightly away from the death spot but none of the inventory remains. Other times it seems to happen independently of broom loss of flight, but this is unclear. Sorry if I'm not posting this in the correct spot.

**Comment by NathanWolf** [comment] 2021-02-16 00:50
Can you please paste the output of `/magic` ?

It will be the full version string. As far as I know this issue should be fixed, but there were a few issues in older versions.

**Comment by Moss-And-Bone** [comment] 2021-02-16 00:54
Maguc 8.3.2-76ea996

**Comment by NathanWolf** [comment] 2021-02-16 00:57
Well sadly I think that would have all the fixes. 
I wonder is it possible they relogged before the server realized they were offline?
Any errors or weird messages in your logs from around that time would be helpful.

**Comment by Moss-And-Bone** [comment] 2021-02-16 01:00
for sure, here is the server console log from just a moment ago when we had a weird crash (I'm new to managing a server so I don't quite understand everything), although it seems to have happened other times without the crash? At least that's what they've said

https://pastebin.com/5AwparUC

**Comment by NathanWolf** [comment] 2021-02-16 01:03
I don't know that those logs are related, but that *does* look really bad- your server was hanging trying to write a (vanilla) player data save file. That player's data is likely corrupted :(

I can't really tell why that would happen though, unless your server is somehow completely out of storage space.

Do you happen to have logs from any of the times this has happened without a server crash being involved?

**Comment by Moss-And-Bone** [comment] 2021-02-16 01:11
That's interesting, huh, was it Netflix's? They're the one this issue seems to occur to the most, is the fix for that to delete their player data and have them reconnect?

We should have a fair amount of storage left, but I will double-check. I'm chatting with my hosting support rn as well

I will ask them for a day it happened and try to comb through those logs to find the relevant output

**Comment by NathanWolf** [comment] 2021-02-16 01:15
Ok thanks, any hints you can give me would be appreciated. As it stands, I'd love to fix this but have no idea what's causing it so I really can't do much.

As for the player data, there's no way to really know, but that Netflix player did try to log in and got kicked while it was going on, so it's possible they were affected.

**Comment by Moss-And-Bone** [comment] 2021-02-16 01:27
Ok after digging deeper they went back to say that there does always seem to be a crash associated, so I will see if I can't find additional logs. I think I need to update Paper as well, and hopefully can get the rest sorted?

We previously didn't have all the right versions of each plugin sorted out which is a likely contributor to the earlier issues, but at present, I think I'm only behind with paper? Hopefully, any of this will be somewhat helpful!

Here is some more log output
https://pastebin.com/Yw4TZt9B
https://pastebin.com/uS4ngLVa

**Comment by NathanWolf** [comment] 2021-02-16 03:10
Ok, good luck! I am hoping it's not something my plugin is doing, but it *is* very hard to tell from here.

That first log is just a bunch of maybe-benign errors from `EnchantmentSolution` (might be nice to show that to the dev of that plugin, though, so they can patch it up)

Second log is hopefully resolved by getting your plugin versions sorted, it indicates that Magic won't work with WorldGuard. This isn't a catastrophic problem, but generally you don't want your protected areas getting blown up by spells (even temporarily) so that would be good to fix.

**Comment by NathanWolf** [comment] 2021-03-04 20:50
I've just released Magic 8.4

I anyone here is still having this issue, please update. I'm not sure if it's fixed, but I'm hoping so. If it is _not_ fixed after updating, please use the following command:

 `/mconfig configure config log_verbosity 100`

This will turn on additional logging. If the death wipe happens, it'd be _extremely_ helpful for me to see the logs around the time of death.

Thank you for your continued patience and support!

**Comment by NathanWolf** [comment] 2021-06-17 17:06
Really hope this is all fixed now.

**Closed by NathanWolf** 2021-06-17 17:06 UTC
Labels: Support
