### ISSUE TITLE
Add papi check to Magic

### ISSUE THREAD

**Issue by Clexus** [elBukkit/MagicPlugin#1236] opened 2023-06-21 10:35 UTC
There is no action like that
%target:placeholder% for target player(if the victim is player)
like %target:player_name%

**Comment by NathanWolf** [comment] 2023-07-10 17:05
This is a duplicate of #1242 

This issue came first, but the newer one has more info so I'm going to close this one.

**Closed by NathanWolf** 2023-07-10 17:05 UTC
