### ISSUE TITLE
Inventory gets deleted on death

### ISSUE THREAD

**Issue by Fflluuffyy** [elBukkit/MagicPlugin#853] opened 2021-02-19 12:17 UTC
Hullo! Enjoying the plugin sofar, but I've come across an issue where the entire inventory gets deleted on death, and all equipped armor and items basically never drop.
Bound items however, aka the wizard hat, the broomstick as well as the wand do stay in the inventory.
 Is this supposed to be intentional?

I am also using a permissions manager, among other things (luckperms) - > could this be the cause of a conflict?

Thank you in advance,

Fflluuffyy

**Comment by NathanWolf** [comment] 2021-02-19 15:05
Definitely not intentional, and not due to luckperms. There were some issues like this but I thought they were fixed.

Is it a reproducible problem with any kind of pattern, or does it happen only randomly sometimes?

What version of Magic and Spigot are you on?

**Comment by Fflluuffyy** [comment] 2021-02-19 19:43
Hi! And thanks again for responding so quickly!

I am running MC 1.16.5 and Magic 8.3.3. I am furthermore running the plugins WorldEdit, WorldGuard, SimpleSethome, SinglePlayerSleep, FlyToggle, Treefeller, as well as Silk Spawner.

So far it has only been happening to me whenever I die under any effect; for example, the effects of fire (from a player's fire aspect), falling from a high place, drowning, and so forth. This furthermore also only happens when I am in my "magic mode". 

What should I do to give a better description? Narrow down the plugins and see if it fixes the issue? Is there a log or config file I can post?
- Fluffy

**Comment by Fflluuffyy** [comment] 2021-02-19 19:49
PS: Another issue I've come across is that with the secure spell, the key that gets added to your inventory has its name in Eldritchtongue; and holding it does not allow you to open your secured chest. This isn't that big of an issue, since the chests can always be unlocked, but I wonder if these two issues are related.

**Comment by NathanWolf** [comment] 2021-02-19 20:04
The secure issue is unfortunately a Spigot bug. I've got a PR in for them to fix it, but I don't know when, if ever, they'll accept it. I should probably try submitting it to Paper as well.

At any rate, I will disable the secure spell for now.

So does this death issue happen reliably, like for instance if you just die from fire you lose all your inventory, every time?

**Comment by Fflluuffyy** [comment] 2021-02-19 20:27
I did some further testing: The death issue happens reliably, and only to me it seems. I am one of two server operators, and the issue always happens when I die due to any reason, while having my magic inventory open.

Furthermore I originally got a wand and enchanted it to the rank of wizard. After concluding testing, I proceeded to destroy the wand and reset my progress. That is everything I did in regards to changing config files/inputting commands.

**Comment by NathanWolf** [comment] 2021-02-19 20:28
If you de-op yourself does it still happen to you?

**Comment by NathanWolf** [comment] 2021-02-19 20:29
It only happening to you is extremely odd and makes me think there's some other plugin doing something special to you (via permissions that you have due to group or op status), but your plugin list is very small and benign-sounding, so I have no suspects.

**Comment by Fflluuffyy** [comment] 2021-02-19 20:47
Yeah, I managed to fix it, the issue was that I had given myself admin permissions on luckperms via the command luckperms.* 

Now everything works as intended since I have removed said permission. Thanks a lot for your help narrowing it down Nathan; I wish you the best of luck and fun with this awesome mod!

-Fluffy

**Comment by NathanWolf** [comment] 2021-02-19 21:21
Hmmmm I'm going to leave this open until I figure it out- that sounds kinda weird. I had already even tested giving myself "*" perms .. I guess it could be some specific plugin you have, but I would like to narrow it down and find a fix on my side.

So any more info you have would be appreciated- is this your full plugin list?

> WorldEdit, WorldGuard, SimpleSethome, SinglePlayerSleep, FlyToggle, Treefeller, as well as Silk Spawner

**Comment by Fflluuffyy** [comment] 2021-02-19 22:12
Yeah I bet it must be frustrating, having thought to have solved perms issues already - but a weird fringe case still causes everything to act up. 
I used "/lp user <your username> permission set luckperms.* true" ; however I didn't do anything past that point.

As soon as I deactivated it via the web editor ("/lp editor") everything started working perfectly fine again. 

And yes, these are the plugins I have - however the only plugin that was using luckperms was Simple Sethome: I was using it to allow multiple homes per player.

**Comment by Moss-And-Bone** [comment] 2021-02-21 03:58
Just wanted to pop in here and say my server is experiencing this again, without the errors from last thread associated. It seems if you die while spell inventory is open, you lose all non-plugin/non-bound items on death without a drop for us. This has happened to three of us on our small server with no associated errors in the server console. Sorry if this isn't the most useful place to put this info, I can move things, also pls let me know if I can provide any other useful info

**Comment by NathanWolf** [comment] 2021-02-21 04:22
That’s a bummer! Does it happen every time you die? If not, is there any pattern to it?

**Comment by Moss-And-Bone** [comment] 2021-02-21 18:10
It doesn't seem to be every time but it's happening most to the three of us that die the most. It seems like 90-100% of the time when one of us dies with spell/saber inventory open it causes no inventory drops on death, but Soulbound enchants and the items from the plugin are all safe (except blasters which are not bound). We had a lightsaber duel which resulted in the killed player not dropping their diamond armor and other items, and other similar things from player, world(fall damage etc) and mob kills.

**Comment by NathanWolf** [comment] 2021-02-23 17:58
Does anyone here having this issue use Yatopia as their server mod?

I'm wondering if this maybe has nothing to do with Magic, and is just this bug here:

https://github.com/YatopiaMC/Yatopia/issues/418

**Comment by Moss-And-Bone** [comment] 2021-02-25 06:27
I don't believe I am, as far as I know, I just use the most recent paper and default config from WinterNode

**Comment by NathanWolf** [comment] 2021-03-04 20:51
I'm going to close this issue to consolidate it with Issue #817 so please use that one going forward.

I'm going to paste the comment I just made there, though, as it's important for this issue:

I've just released Magic 8.4

I anyone here is still having this issue, please update. I'm not sure if it's fixed, but I'm hoping so. If it is _not_ fixed after updating, please use the following command:

 `/mconfig configure config log_verbosity 100`

This will turn on additional logging. If the death wipe happens, it'd be _extremely_ helpful for me to see the logs around the time of death.

Thank you for your continued patience and support!

**Closed by NathanWolf** 2021-03-04 20:51 UTC
Labels: Bug
