### ISSUE TITLE
Console's error when i drop the wand. Check please.

### ISSUE THREAD

**Issue by InDeeDy** [elBukkit/MagicPlugin#143] opened 2016-08-08 20:36 UTC
######This is screenshots of my error:
![1](https://cloud.githubusercontent.com/assets/20488890/17495038/1214e2a0-5dc0-11e6-9418-51ec3d74b743.jpg)
![2](https://cloud.githubusercontent.com/assets/20488890/17495039/1215dcdc-5dc0-11e6-95b1-5fa0e56a3ce0.jpg)
##likely this is caused by drop the wand in extra y. 
![screenshot_9](https://cloud.githubusercontent.com/assets/20488890/17495225/ebc9dac8-5dc0-11e6-98cd-b640ba2534ea.png)

**Comment by NathanWolf** [comment] 2016-08-08 20:44
I have removed that velocity completely- I considered limiting it (I think that event is repeating and so the velocity increases each time...) but decided to just remove it because I've been meaning to do that anyway. I've had issues with it in the past, player's wands get lost because someone else walks over them and they fly away.

The fix is in Magic dev build #1704, whenever it finishes building.

This will definitely fix the exception in your first screenshot. Whether this is related to the server crash in your second screenshot I can't say- I suppose if a bad velocity got through the internal Spigot check it might crash vanilla code, but can't be sure what the cause is there.

**Comment by InDeeDy** [comment] 2016-08-09 08:57
So, when you build the fixed version? I realy scared for online (900)

**Comment by NathanWolf** [comment] 2016-08-09 14:40
http://jenkins.elmakers.com/job/MagicPlugin/1704/com.elmakers.mine.bukkit.plugins$Magic/artifact/com.elmakers.mine.bukkit.plugins/Magic/6.3-SNAPSHOT/Magic-6.3-SNAPSHOT.jar

**Comment by InDeeDy** [comment] 2016-08-10 07:38
Oh... i have another problem. Its not compatible with 1.8.8 (With ViaVersion). Can you add a 1.8 support, please :(

**Comment by InDeeDy** [comment] 2016-08-12 20:01
:(

**Comment by NathanWolf** [comment] 2016-08-12 20:03
The 5.5.x builds are the ones you need for 1.8. 

http://jenkins.elmakers.com/job/MagicPlugin-1.8/

**Closed** 2016-10-10 03:24 UTC
