### ISSUE TITLE
Issues with spawning wands

### ISSUE THREAD

**Issue by Svennieboy777** [elBukkit/MagicPlugin#622] opened 2019-12-28 19:51 UTC
Hello,

All the appreciate wands do not seem to work, it says unknown item?
Also, if i use the broomstick my server crashes randomly and some wands cause spam in my console.

Can you look into it?

```
Description: Exception in server tick loop

java.lang.AssertionError: TRAP
	at net.minecraft.server.v1_15_R1.ItemStack.checkEmpty(ItemStack.java:86)
	at net.minecraft.server.v1_15_R1.ItemStack.setCount(ItemStack.java:864)
	at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:404)
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1309)
	at net.minecraft.server.v1_15_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:28)
	at net.minecraft.server.v1_15_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1)
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19)
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144)
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118)
	at net.minecraft.server.v1_15_R1.MinecraftServer.aZ(MinecraftServer.java:917)
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:910)
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127)
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:894)
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:827)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.15.1
	Minecraft Version ID: 1.15.1
```

**Comment by alekso56** [comment] 2019-12-29 16:10
Duplicate of #327 
This plugin is not compatible with creative mode.

**Comment by Svennieboy777** [comment] 2019-12-29 18:29
> Duplicate of #327
> This plugin is not compatible with creative mode.

It worked in the 1.14 update.

**Comment by NathanWolf** [comment] 2019-12-29 18:33
This plugin has never been compatible with creative mode.

If you have issues spawning specific wands *in survival* please show the commands you're using.

**Comment by Svennieboy777** [comment] 2019-12-29 18:39
> This plugin has never been compatible with creative mode.
> 
> If you have issues spawning specific wands _in survival_ please show the commands you're using.

I am in survival, if i spawn a wand the following error shows up in the console:
29.12 13:38:28 [Server] Server thread/INFO Svennieboy777 issued server command: /wand create appreciate_appreciate
29.12 13:38:28 [Server] Server thread/WARN java.lang.NullPointerException
29.12 13:38:28 [Server] Server thread/WARN at com.elmakers.mine.bukkit.wand.Wand.addSpellLore(Wand.java:3003)
29.12 13:38:28 [Server] Server thread/WARN at com.elmakers.mine.bukkit.wand.Wand.getLore(Wand.java:2607)
29.12 13:38:28 [Server] Server thread/WARN at com.elmakers.mine.bukkit.wand.Wand.updateLore(Wand.java:2651)
29.12 13:38:28 [Server] Server thread/WARN at com.elmakers.mine.bukkit.wand.Wand.<init>(Wand.java:331)
29.12 13:38:28 [Server] Server thread/WARN at com.elmakers.mine.bukkit.magic.MagicController.getWand(MagicController.java:3872)
29.12 13:38:28 [Server] Server thread/WARN at com.elmakers.mine.bukkit.wand.Wand.createWand(Wand.java:3290)
29.12 13:38:28 [Server] Server thread/WARN at com.elmakers.mine.bukkit.magic.MagicPlugin.createWand(MagicPlugin.java:427)
29.12 13:38:28 [Server] Server thread/WARN at com.elmakers.mine.bukkit.magic.command.WandCommandExecutor.onWandCreate(WandCommandExecutor.java:700)
29.12 13:38:28 [Server] Server thread/WARN at com.elmakers.mine.bukkit.magic.command.WandCommandExecutor.processWandCommand(WandCommandExecutor.java:377)
29.12 13:38:28 [Server] Server thread/WARN at com.elmakers.mine.bukkit.magic.command.WandCommandExecutor.onCommand(WandCommandExecutor.java:103)
29.12 13:38:28 [Server] Server thread/WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
29.12 13:38:28 [Server] Server thread/WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
29.12 13:38:28 [Server] Server thread/WARN at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:711)
29.12 13:38:28 [Server] Server thread/WARN at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1657)
29.12 13:38:28 [Server] Server thread/WARN at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1497)
29.12 13:38:28 [Server] Server thread/WARN at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
29.12 13:38:28 [Server] Server thread/WARN at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
29.12 13:38:28 [Server] Server thread/WARN at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19)
29.12 13:38:28 [Server] Server thread/WARN at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)
29.12 13:38:28 [Server] Server thread/WARN at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144)
29.12 13:38:28 [Server] Server thread/WARN at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
29.12 13:38:28 [Server] Server thread/WARN at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118)
29.12 13:38:28 [Server] Server thread/WARN at net.minecraft.server.v1_15_R1.MinecraftServer.aZ(MinecraftServer.java:917)
29.12 13:38:28 [Server] Server thread/WARN at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:910)
29.12 13:38:28 [Server] Server thread/WARN at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127)
29.12 13:38:28 [Server] Server thread/WARN at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:894)
29.12 13:38:28 [Server] Server thread/WARN at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:827)
29.12 13:38:28 [Server] Server thread/WARN at java.lang.Thread.run(Thread.java:748)

**Comment by NathanWolf** [comment] 2019-12-29 19:17
Sorry, this may be a little confusing. The `/wand create` command turns the item you're holding into a wand. What were you holding when you ran this command? It has a check for you not holding an item, so I'm not sure how you hit this error.

To spawn one of your "apprentice_appreciate" wand you just use `/wand apprentice_appreciate`. If you still have problems with that then please paste the config of that wand template.

**Comment by Svennieboy777** [comment] 2019-12-29 20:06
> Sorry, this may be a little confusing. The `/wand create` command turns the item you're holding into a wand. What were you holding when you ran this command? It has a check for you not holding an item, so I'm not sure how you hit this error.
> 
> To spawn one of your "apprentice_appreciate" wand you just use `/wand apprentice_appreciate`. If you still have problems with that then please paste the config of that wand template.

I still have the same issue. Let me copy it:
`#
# Modify this file to change the available default wands.
# New wands can be added, existing wands modified or removed (disabled)
#
# You can also add individual files to the wands/ folder
#
# To see the current default builtin configs, look in this folder:
# https://github.com/elBukkit/MagicPlugin/tree/master/Magic/src/main/resources/defaults/wands
#
# For customization help see:
# https://github.com/elBukkit/MagicPlugin/wiki/Customization
#

#
# This is the Wand configuration file for the Magic plugin.
#
# This defines all of the wand "templates" that can be created with the
# /wand and /wandp commands.
#
# Once a wand is created, it is its own unique item. It may be modified after that,
# and may bear no direct relationship back to the template that created it.
#
# The name and description, of a wand should be defined in messages.yml as
#  messages.wands.<wandkey>.name
#  messages.wands.<wandkey>.description
#
# Note that wands can also be renamed on an anvil.
#
# There are two special entries in here:
# - The "default" wand is used as a template when creating a new and with /wand.
# - The "random" wand has a different and specific configuration format.
#
# General format:
#
# <wandkey>:
#
#       # If true, this wand can not be enchanted, combined or otherwise modified
#
#       modifiable: true
#
#       # Set to false to disable a preset wand
#       enabled: <true|false>
#
#       # Casting cost and cooldown reduction
#
#       cost_reduction: (0.0-1.0)
#       cooldown_reduction: (0.0-1.0)
#
#       # Overall and specific protection
#
#       protection: (0.0-1.0)
#       protection_physical: (0.0-1.0)
#       protection_fire: (0.0-1.0)
#       protection_falling: (0.0-1.0)
#       protection_blast: (0.0-1.0)
#
#       # Regeneration values are added every second
#
#       health_regeneration: (0-20)
#       hunger_regeneration: (0-20)
#
#       # If non-zero, this wand will use the Mana system instead of XP
#
#       xp_regeneration: (0-200)
#       xp_max: (0-?)
#
#       # This provides bonus damage and effects to some spells
#       # and increases the overall range of all targeted spells
#
#       power: (0.0-1.0)
#
#       # Increases player walk/fly speed- is limited by Bukkit
#
#       haste: (0.0 - 0.4-ish)
#
#       # Applies a potioneffect to the player while holding the wand
#       # also used by many spells that have visual effects when cast with this wand
#
#       effect_color: <hex color, eg 'FF0000')
#       spells:
#           - <spellname>
#       materials:
#           - <materialname>
#

#
# Examples:
# Note that a "#" character means the line is commented out and has no effect.
# Make sure to not comment out the lines you add, there should not be a space in front of the name, indentation is important.
# Use http://www.yamllint.com if you have issues with your config, make sure not to use tabs!
#

# Change starting mana of default wand
# Note that wand progression (when upgraded/enchanted) is defined in enchanting.yml
# wand:
#    mana_max: 100
#    mana: 100
#    mana_regeneration: 10



starter:
    effect_color: random
    icon: stick
    glow: true
    max_enchant_count: 3
    path: beginner
    xp_max: 50
    xp: 50
    xp_regeneration: 5
    quiet: 1
    bound: true
    keep: false
    undroppable: false
    indestructible: false
    effect_bubbles: false
    active_spell: missile
    spells:
     - missile

student:
    effect_color: '00FF00'
    icon: gold_axe
    path: student
    bound: true
    keep: true
    undroppable: true
    indestructible: true
    xp_regeneration: 30
    protection_falling: 0.5
    xp_max: 150
    xp: 150
    spells:
      - missile
      - blink
      - arrowrain
      - boom
      - familiar
      - fling
      - fire
      - frost
      - grenade
      - heal
      - monster
      - lightning
      - lava
      - portal
      - stream
      - flamethrower
      - wither
      - mine
      - chop
      - shell
      - tag
      - blob
      - disarm
      - entangle
      - poison
      - laser
      - tracking
      - rocket
      - shrink

apprentice:
    effect_color: '22FF22'
    icon: gold_axe
    path: apprentice
    indestructible: true
    bound: true
    keep: true
    undroppable: true
    xp_regeneration: 40
    xp_max: 200
    xp: 200
    protection_falling: 0.8
    protection_physical: 0.8
    protection_fire: 0.5
    protection_explosions: 0.5
    effect_bubbles: true
    spells:
      - missile
      - blink
      - arrowrain
      - boom
      - familiar
      - fling
      - fire
      - frost
      - grenade
      - heal
      - monster
      - lightning
      - lava
      - portal
      - stream
      - flamethrower
      - wither
      - mine
      - chop
      - shell
      - tag
      - blob
      - disarm
      - entangle
      - poison
      - laser
      - tracking
      - rocket
      - shrink
      - emp
      - blessing
      - breach
      - disintegrate
      - force
      - hat
      - music
      - sandblast
      - phase
      - grow
      - counterspell
      - tent
      - disc
      - rubberize
      - wound
      - harden
      - sponge
      - flashbang
      - gatling
      - walls

master:
    path: master
    icon: gold_pickaxe
    xp_regeneration: 50
    xp_max: 250
    xp: 250
    effect_particle: town_aura
    effect_particle_count: 2
    keep: true
    bound: true
    undroppable: true
    indestructible: true
    protection_falling: 1
    protection_physical: 0.8
    protection_fire: 0.8
    protection_explosions: 0.8
    effect_bubbles: true
    spells:
      - missile
      - blink
      - arrowrain
      - boom
      - familiar
      - fling
      - fire
      - frost
      - grenade
      - heal
      - monster
      - lightning
      - lava
      - portal
      - stream
      - flamethrower
      - wither
      - mine
      - chop
      - shell
      - tag
      - blob
      - disarm
      - entangle
      - poison
      - laser
      - tracking
      - rocket
      - shrink
      - emp
      - blessing
      - breach
      - disintegrate
      - force
      - hat
      - music
      - sandblast
      - phase
      - grow
      - counterspell
      - tent
      - disc
      - rubberize
      - wound
      - harden
      - sponge
      - flashbang
      - gatling

base_wand:
    drop: cycle_hotbar
    left_click: cast
    right_click: toggle
    swap: none
    mode: inventory
`

**Comment by NathanWolf** [comment] 2019-12-30 01:17
If you are trying to get the apprentice wand (which I think is built in, no configs needed) you just use `/wand apprentice`.  

If that's not working, please tell me the message you receive in-game and anything that shows up in the server logs/console when you use that command.

**Closed** 2020-08-20 18:09 UTC
Labels: Bug, Integration
