### ISSUE TITLE
Broomstick and invisibility spell issues.

### ISSUE THREAD

**Issue by Pankoloso** [elBukkit/MagicPlugin#888] opened 2021-03-28 15:39 UTC
Broomstick: When broomstick is swaped with other item in inventory it can sometimes delete item it's swaped with and return to original item slot.

Invisibility spell: When it's active and armor is swaped, sometimes it will couse to duplicate that piece of armor.

**Comment by NathanWolf** [comment] 2021-03-28 17:18
Can you please provide some more information?

1. Do you mean while riding the broomstick? If so, how are you moving the broomstick handle (hotbar keys, clicking, dragging, etc?) it should be completely immovable.

2. Kind of same question, how are you swapping armor? Your armor should all be hidden but come back when the spell ends or if you click on the inventory slot.

**Comment by Pankoloso** [comment] 2021-03-28 18:29
1.(I was moving it by clicking, not when riding broomstick) When moving in inventory it can move back to inventory slot it was before eresing item it was swaped with. In other words when you are sorting inventory it can go back where it was placed before, eresing item placed there.

2. When I used invisibility spell for first time it places pumpkin seeds in my armor slots and when i clicked one of them it duplicated armor items I had on like rocket boots. 

I hope it will help, if you will need me to be even more specific with information I will responde as quicly I can.

**Comment by NathanWolf** [comment] 2021-03-28 18:37
Both of these sound pretty strange- the broomstick (or any wand item) shouldn’t do anything special like that.

What version of the plugin are you on? (You can use /magic to see)

And for #2- when the cloak spell starts it should replace your armor with the seeds, clicking on the seeds brings the armor back but you wouldn’t have had the original.. are you saying when you click the seeds you get two back? Or the original one was placed in your inventory somewhere instead of getting replaced by seeds?

**Comment by NathanWolf** [comment] 2021-03-28 19:13
Oh, and just to double-check, you are not in creative mode, right?

**Comment by Pankoloso** [comment] 2021-03-28 19:20
I was not in creative mode.

The version should be latest I added it yesterday, sorry I can't check exact version right now.

and for 2. I clicked on seed and I got two back, one in armor slot and second one in inventory.

**Comment by NathanWolf** [comment] 2021-03-30 02:14
I checked the Cloak issue and could not reproduce it in the latest dev build. It's possible some bug made it into a release, so if you let me know your exact version# I can try out that version.

Or if you'd rather, you could see if the issue persists on the latest dev build:

https://jenkins.elmakers.com/job/MagicPlugin/

However, the issue you described with the broomstick sounds like something else, I would have no idea what that could be. If you do try the dev build, let me know if that's still happening too.

**Comment by Pankoloso** [comment] 2021-03-31 07:35
I checked the dev build and neither of issues showed up. May i close this issue or there is something else that you would need?

**Comment by NathanWolf** [comment] 2021-03-31 14:58
Weird. Well thank you for the feedback! Guess I should try to get that released ASAP :)

**Closed by NathanWolf** 2021-03-31 14:58 UTC
Labels: Support
