### ISSUE TITLE
Broomsticks throw an error when in creative mode

### ISSUE THREAD

**Issue by downboy** [elBukkit/MagicPlugin#327] opened 2018-02-26 19:11 UTC
I still love the plugin, but i have a small issue with a broomstick, i have a error thats showing in console!

```
[20:08:18 FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.AssertionError: TRAP
at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_161]
at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_161]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:47) [server.jar:git-Spigot-596221b-9a1fc1e]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [server.jar:git-Spigot-596221b-9a1fc1e]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [server.jar:git-Spigot-596221b-9a1fc1e]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [server.jar:git-Spigot-596221b-9a1fc1e]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [server.jar:git-Spigot-596221b-9a1fc1e]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.AssertionError: TRAP
at net.minecraft.server.v1_12_R1.ItemStack.F(ItemStack.java:100) ~[server.jar:git-Spigot-596221b-9a1fc1e]
at net.minecraft.server.v1_12_R1.ItemStack.setCount(ItemStack.java:831) ~[server.jar:git-Spigot-596221b-9a1fc1e]
at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:413) ~[server.jar:git-Spigot-596221b-9a1fc1e]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:997) ~[server.jar:git-Spigot-596221b-9a1fc1e]
at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:26) ~[server.jar:git-Spigot-596221b-9a1fc1e]
at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) ~[server.jar:git-Spigot-596221b-9a1fc1e]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) ~[server.jar:git-Spigot-596221b-9a1fc1e]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_161]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_161]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[server.jar:git-Spigot-596221b-9a1fc1e]
... 5 more
```
The error is only when im in gamemode creative.
i hope you can fix it, i will report more errors and stuff if i find them!

**Comment by NathanWolf** [comment] 2018-02-26 19:20
Hm- seems odd, something is setting the item count to 0. But Magic itself doesn't really do that, and I don't see any magic stuff in the stack trace.

Could you please provide some more info? 

Is this spigot, or Paper? 
Does this happen every time you ride a broom? 
Does it happen on mount, dismount, crash or other?
Can you do "/magic" and let me know the version info it shows?

If I can get enough info to reproduce the problem I can likely fix it.

**Comment by killme** [comment] 2018-02-27 13:24
Looks like a fun bug, the vanilla interaction handler is returning the magical "empty" item stack. And the player interaction handler is trying to update its count. Perhaps a paper/spigot/vanilla bug?

**Comment by downboy** [comment] 2018-02-27 18:22
Is this spigot, or Paper? **Spigot**
Does this happen every time you ride a broom? **yes only if im in gamemode creative**
Does it happen on mount, dismount, crash or other? **on mount i see the error and not on dismount or crash**
Can you do "/magic" and let me know the version info it shows? **Magic 7.1.5-4e9ef**

**Comment by NathanWolf** [comment] 2018-02-27 18:27
Ahhhh creative. Yeah I can reproduce that.

I'll keep this open, but basically creative mode and Magic don't generally get along.

**Comment by NathanWolf** [comment] 2018-04-30 16:26
This is a known Spigot bug, I am trying to get it looked at again here:

https://hub.spigotmc.org/jira/browse/SPIGOT-3020

**Comment by NathanWolf** [comment] 2020-12-14 21:16
I disallowed using brooms while in creative mode. It doesn't seem like the core issue is ever getting fixed on the Spigot side.

**Closed by NathanWolf** 2020-12-14 21:16 UTC
Labels: Bug, Spigot Issue, Unlikely
