### ISSUE TITLE
Blasters not following enchanting paths

### ISSUE THREAD

**Issue by Curtis73** [elBukkit/MagicPlugin#208] opened 2017-03-05 11:16 UTC
Hey there,
I've made a custom enchanting path to go with the blaster, but whenever I cast spellshop with it, it says 'you have nothing to learn with this blaster'.
Am I doing something wrong?
Here is the blaster:
`blaster:
    icon: wood_hoe:12
    path: cadet
    mode: inventory
    drop: toggle
    left_click: none
    right_click: toggle
    swap: cycle_hotbar
    locked: true
    quick_cast: true
    quiet: 2
    mana: 100
    mana_max: 100
    mana_regeneration: 10
    indestructible: true
    spells:
        - blaster`

**Comment by NathanWolf** [comment] 2017-03-05 15:37
Can you please paste both the blaster and cadet path configs inside some code blocks (<> button in the toolbar up there)?

You may need to remove "locked: true" but I'm not 100% sure on that.

**Comment by Curtis73** [comment] 2017-03-05 16:36
Cadet:

`cadet:
    inherit: default
    max_mana: 500
    max_mana_regeneration: 50
    mana_regeneration:
      1: 100
    mana_max:
      2: 100
    spell_count:
      1: 100
    spells:
      frost: 1
      flashbang: 1
      missile: 1
      blaster: 1
trooper:
    inherit: cadet
    max_mana: 500
    max_mana_regeneration: 50
    mana_regeneration:
      1: 100
    mana_max:
      2: 100
    spell_count:
      1: 100
    spells:
      gatling: 1
      blast: 1
      flare: 1

private:
    inherit: trooper
    max_mana: 500
    max_mana_regeneration: 50
    mana_regeneration:
      1: 100
    mana_max:
      2: 100
    spell_count:
      1: 100
    spells:
      homing: 1
      cluster: 1

sergeant:
    inherit: private
    max_mana: 500
    max_mana_regeneration: 50
    mana_regeneration:
      1: 100
    mana_max:
      2: 100
    spell_count:
      1: 100
    spells:
      flamethrower: 1
      arrowrain: 1
      icbm: 1
      capture: 1

lieutenant:
    inherit: sergeant
    max_mana: 500
    max_mana_regeneration: 50
    mana_regeneration:
      1: 100
    mana_max:
      2: 100
    spell_count:
      1: 100
    spells:
      railgun: 1
      sticky: 1

commander:
    inherit: lieutenant
    max_mana: 500
    max_mana_regeneration: 50
    mana_regeneration:
      1: 100
    mana_max:
      2: 100
    spell_count:
      1: 100
    spells:
      meteor: 1
      shell: 1`

I don't have a blaster in my paths.

**Comment by NathanWolf** [comment] 2017-03-05 17:39
Doh, could you please edit that and replace the ` with ``` ?

If not I can probably figure it out :) I'll have to try out these configs when I can- but also try removing "locked: true" from configs, or in-game use "/wand unlock" on a Blaster and see if it can then be upgraded?

**Comment by Curtis73** [comment] 2017-03-05 18:00
Aha - unlocking it did the trick :)
Thanks!

**Comment by Curtis73** [comment] 2017-03-05 18:33
And for some reason whenever I attempt to go up a level it throws up 'you must learn $power to advance'.

**Comment by NathanWolf** [comment] 2017-03-05 18:42
That's real weird - I'll check your configs when I can. Please remind me what version of Magic you are on?

**Comment by Curtis73** [comment] 2017-03-05 18:47
I'm on magic 6.7

**Comment by NathanWolf** [comment] 2017-03-05 21:38
Hm, so I'm not sure but I think I may have made some recent fixes in this area... it may be worth trying to update to the latest dev build.

I tried your configs out and it seemed to work, or at least I could get all the way through the Cadet path. I then got a message there "There is nothing more for you here" when using the spellshop.

If you want the paths to upgrade you have to add an "upgrade" property to each path, like "upgrade: trooper" to the cadet path, but I wasn't sure if that's what you wanted.

In any case I couldn't reproduce that weird message with "$power" in it, and I'm really wondering where that is coming from :(

I'm also going to take a look at the "locked" thing.. I think my intention was that locked wands were still upgradeable if they were on a path.

**Comment by NathanWolf** [comment] 2017-03-06 04:16
After some looking and tinkering, I changed my mind and it is not intended for the spellshop to work with locked wands. There is an "allow_locked" parameter for shops, though, so I think that covers all the bases.

The "You must learn $power" message was a bad search+replace job in messages.yml, I just pushed a fix for that- you can also fix it yourself in configs by adding this:
```
spell:
    required_spell: "You must learn &r&4$spell &d&oto advance"
```

That should only appear if you've got a required_spells block on your paths, though, so I'm still a little confused as to why you saw it, given the configs you showed me.

Please let me know or re-open this if you're still having trouble!

**Closed by NathanWolf** 2017-03-06 04:16 UTC
