### ISSUE TITLE
CME on Block Undo in  1.14.3

### ISSUE THREAD

**Issue by Yukyxy** [elBukkit/MagicPlugin#530] opened 2019-07-09 12:38 UTC
Hello I have this error https://pastebin.com/VAzTL1qt

**Comment by NathanWolf** [comment] 2019-07-09 22:17
That kind of looks like an internal Spigot/MC error. Does this happen consistently?

**Comment by Yukyxy** [comment] 2019-07-10 12:11
yes frequently

**Comment by NathanWolf** [comment] 2019-10-09 20:43
Sorry for never coming back to this, but I never did see this problem myself. Do you know if it's still happening?

**Comment by NathanWolf** [comment] 2020-08-20 18:33
I still couldn't ever reproduce this, going to close the issue until it comes back up again.

**Closed by NathanWolf** 2020-08-20 18:33 UTC
Labels: Bug, Spigot Issue
