### ISSUE TITLE
"Mount" on Phantom causes player disconnected and not able to join again.

### ISSUE THREAD

**Issue by k-jiang** [elBukkit/MagicPlugin#541] opened 2019-07-21 15:01 UTC
Description: When player use "Mount" spell to ride a Phantom then "shift" to unmount, the player will disconnected from the server and not able to join again.

```
[20:13:25] [Server thread/INFO]: k_jiang lost connection: Invalid move player packet received
[20:13:25] [Server thread/INFO]: [Heroes] Saved hero: k_jiang
[20:13:25] [Server thread/INFO]: k_jiang left the game
[20:13:25] [Server thread/WARN]: handleDisconnection() called twice
```
When player try to join the server again, this happened:
```
[22:38:23 INFO]: UUID of player k_jiang is c726210d-3489-4e00-9aca-d3f427d7b294
[22:38:23 INFO]: k_jiang[/xx.xx.xx.xx:xxxxx] logged in with entity id 1495785 at ([world]NaN, NaN, NaN)
[22:38:27 INFO]: k_jiang lost connection: Invalid move player packet received
[22:38:27 INFO]: [Heroes] Saved hero: k_jiang
[22:38:27 INFO]: Moon_Suger left the game
[22:38:27 WARN]: handleDisconnection() called twice
```

Unless we delete the saved data from `world/playerdata` folder, the player is not able to join the server no matter how.

Tested with:
Magic `Magic 7.7.4-fd3f986`
Heroes `Heroes v1.9.3-SNAPSHOT-72c1c55`
PaperSpigot `This server is running Paper version git-Paper-639 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)`

We disabled `spell` from our server for this time being. This bug might related to #92, though we don't have server crashes.

**Comment by NathanWolf** [comment] 2019-07-30 21:58
I could not reproduce this on Spigot 1.14.4 - I'm guessing this might have been an internal spigot bug that was fixed.

Sorry for the late response, if you're still having this issue could you try again?

**Comment by leveljaap** [comment] 2019-08-16 04:57
Hello, I'm kinda late to the party but I wanted to say I have the exact same issue. I solved it by removing the playerdata of the players who weren't able to join (aka me). It doesn't happen all the time you try to dismount phantoms but sometimes it does.

**Comment by NathanWolf** [comment] 2019-09-24 00:15
I'm hoping this was fixed by Spigot- I can't reproduce it anymore. Are either of you still having this issue?

**Closed** 2019-10-09 20:25 UTC
Labels: Bug, MC Version
